spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_security?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #resources:
    #static-locations: classpath:/*
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #static 文件夹下的静态文件访问路径
  #mvc.static-path-pattern: /**
    #thymeleaf end
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            tablePrefix: qrtz_
            misfireThreshold: 60000
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis-plus:
  mapper-locations: classpath:com/lmk/springsecuritydemo/**/mapper/*Mapper.xml
  type-aliases-package: com.lmk.springsecuritydemo.**.entity
  configuration:
    mapUnderscoreToCamelCase: true # 驼峰命名
    autoMappingBehavior: FULL # 开启字段自动映射（必需）

server:
  port: 8080
  servlet:
    context-path: /spring_security_demo
    session:
      timeout: 14400s
      cookie:
        secure: false
        http-only: true

cxf:
  path: /soap

swagger:
  enable: true
